### ISSUE TITLE
kick-message config.yml not working properly.

### ISSUE THREAD

**Issue by Tjonna** [xImAnton/minecraft-discord-verification#10]
Hey there, everyone works smoothly on my Paper Server.

However, I keep getting "You are not verified" even though in my config I tried to change it multiple times. 
If I change Discord token, or Guild ID everything works. But the kick message stays the same.

Also, thanks for v1.2 :)

**Comment by xImAnton** [comment]
It is possible that you still have the old config.yml? The new key for the kick message is `messages.not-verified`.
Try to delete the config file and let it generate a new one!

**Comment by Tjonna** [comment]
> It is possible that you still have the old config.yml? The new key for the kick message is `messages.not-verified`. Try to delete the config file and let it generate a new one!

Yes, it would seem I've made a mistake. My bad.
