### ISSUE TITLE
Banned Players that are Verified can still join the server.

### ISSUE THREAD

**Issue by Tjonna** [xImAnton/minecraft-discord-verification#11]
Hi there, so as the title mentioned. If you're verified nothing is stopping you from joining.

Maybe also whitelist servers?

**Comment by Tjonna** [comment]
I also tested it by removing the plugin, afterwards I could not enter anymore.

**Comment by xImAnton** [comment]
should be fixed now

**Comment by Tjonna** [comment]
> should be fixed now

Doesn't seem to work for me. Are you sure? I did a completely fresh install on a paper server.

**Comment by xImAnton** [comment]
Have you used the new release? I'm very sure it should work now, couldn't reproduce this in my test environment.
