### ISSUE TITLE
[Suggestion] Add option to add a role to verified Users. 

### ISSUE THREAD

**Issue by vinc3nz** [xImAnton/minecraft-discord-verification#13]
Add support to add a role that verified User will get if they verify through Discord. And remove the role if the unverify.

**Comment by xImAnton** [comment]
I'm currently not able to work on this but I can add it in probably three weeks. ✌️

**Comment by xImAnton** [comment]
sorry for the big delay, i will upload a release jar later this night. if you encounter any problem, let me know
