### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by Tjonna** [xImAnton/minecraft-discord-verification#7]
My apologies if my issue is irrelevant, however I downloaded the jar freshly and could not follow the installation steps you mentioned, after googling for a bit it really seems to be the plugin itself missing something. 

The error:
Could not load 'plugins\discord-verification.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

To recreate:
Placed the jar into my plugins folder, I'm running it with BungeeCord activated & a Paper server.

**Comment by xImAnton** [comment]
Hi!

This is a bungeecord plugin, you need to put it into the plugins folder of your bungeecord proxy server.
If you haven't got one, it won't work. 

But this gives me the idea, to make it also work on a single paper server. If you can wait a few days, I could add this.

Greetings
Anton

**Comment by Tjonna** [comment]
Yes, for sure. Thanks for the razor fast reply, much appreciated.

**Comment by xImAnton** [comment]
Now it should work on a paper server!
You can close the issue if it works. If not, let me know. 😅
