### ISSUE TITLE
Make also work as Bukkit plugin

### ISSUE THREAD

**Issue by xImAnton** [xImAnton/minecraft-discord-verification#8]
Sometimes you don't have a bungeecord proxy in place (#7), so it would be good if this worked on a single minecraft server as well.

For using the same jar as bukkit and bungee plugin at the same time, we need a `plugin.yml` file. (https://www.spigotmc.org/threads/merging-bukkit-and-bungee-plugin-jars.23591/)

**Comment by Tjonna** [comment]
👍

**Comment by xImAnton** [comment]
Added in release [v1.2](https://github.com/xImAnton/minecraft-discord-verification/releases/tag/v1.2)

**Comment by Tjonna** [comment]
Appreciate it
